" Colorscheme generated by https://github.com/arcticlimer/djanho
highlight clear

function s:highlight(group, bg, fg, style)
  let gui = a:style == '' ? '' : 'gui=' . a:style
  let fg = a:fg == '' ? '' : 'guifg=' . a:fg
  let bg = a:bg == '' ? '' : 'guibg=' . a:bg
  exec 'hi ' . a:group . ' ' . bg . ' ' . fg  . ' ' . gui
endfunction

let s:Color7 = '#F8F8F0'
let s:Color11 = '#49483e'
let s:Color12 = '#5d5d5d'
let s:Color13 = '#0c0c0c'
let s:Color1 = '#A6E32D'
let s:Color10 = '#f8f8f2'
let s:Color4 = '#2499DA'
let s:Color9 = '#000000'
let s:Color0 = '#616671'
let s:Color8 = '#DE0059'
let s:Color6 = '#3EFF9E'
let s:Color2 = '#F129FF'
let s:Color5 = '#F92672'
let s:Color3 = '#9CFFFF'

call s:highlight('Comment', '', s:Color0, '')
call s:highlight('String', '', s:Color1, '')
call s:highlight('Number', '', s:Color2, '')
call s:highlight('Identifier', '', s:Color3, '')
call s:highlight('Keyword', '', s:Color4, 'bold')
call s:highlight('Type', '', s:Color5, '')
call s:highlight('Function', '', s:Color6, '')
call s:highlight('Error', s:Color5, s:Color7, '')
call s:highlight('Operator', '', s:Color8, 'bold')
call s:highlight('StatusLine', '', s:Color9, '')
call s:highlight('WildMenu', s:Color9, s:Color10, '')
call s:highlight('Pmenu', s:Color9, s:Color10, '')
call s:highlight('PmenuSel', s:Color10, '', '')
call s:highlight('PmenuThumb', s:Color9, s:Color10, '')
call s:highlight('Normal', s:Color9, s:Color10, '')
call s:highlight('Visual', s:Color11, '', '')
call s:highlight('CursorLine', s:Color11, '', '')
call s:highlight('ColorColumn', s:Color11, '', '')
call s:highlight('SignColumn', s:Color9, '', '')
call s:highlight('LineNr', '', s:Color12, '')
call s:highlight('TabLine', s:Color13, '', '')
call s:highlight('TabLineFill', s:Color13, '', '')
call s:highlight('TSPunctDelimiter', '', s:Color10, '')

highlight! link TSOperator Operator
highlight! link TSFunction Function
highlight! link TSNamespace TSType
highlight! link TSConstBuiltin TSVariableBuiltin
highlight! link TSString String
highlight! link TSFuncMacro Macro
highlight! link TSNumber Number
highlight! link TSParameterReference TSParameter
highlight! link TSParameter Constant
highlight! link Folded Comment
highlight! link Whitespace Comment
highlight! link TSLabel Type
highlight! link TSTag MyTag
highlight! link TSRepeat Repeat
highlight! link TSComment Comment
highlight! link Operator Keyword
highlight! link TSProperty TSField
highlight! link TSField Constant
highlight! link CursorLineNr Identifier
highlight! link TelescopeNormal Normal
highlight! link TSPunctBracket MyTag
highlight! link TSKeyword Keyword
highlight! link TSConstant Constant
highlight! link TSType Type
highlight! link Repeat Conditional
highlight! link TSPunctSpecial TSPunctDelimiter
highlight! link NonText Comment
highlight! link TSFloat Number
highlight! link Macro Function
highlight! link TSTagDelimiter Type
highlight! link Conditional Operator
highlight! link TSConditional Conditional
